# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: MIDIMonster
version: "0.0.2a.001"
slug: midimonster
description: Use MIDI devices in Home Assistant
url: "https://github.com/morrisb74/ha-addons/tree/main/midimonster"
stage: experimental
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
services: 
  - mqtt:need
apparmor: false
full_access: true
ports:
  5004/udp: 5004
  5003/udp: 5003
ports_description:
  5004/udp: RTPMidi Session
  5003/udp: RTPMidi Control
#host_network: true
#privileged: 
#  - SYS_RESOURCE
#udev: true
#host_dbus: true
#devices:
#  - /dev/snd/seq
init: false
audio: false
map:
  - config:rw
#image: "ghcr.io/home-assistant/{arch}-addon-example"
